spring:
  datasource:
    url: jdbc:mysql://47.113.218.236/INF_system?useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: jhy123
  data:
    redis:
      database: 0
      host: 47.113.218.236
      port: 6379
      password: jhy123
  mail:
    username: 15358755057@163.com
    password: BHCYEUFXXRHASIGZ
    host: smtp.163.com
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    host: 47.113.218.236
    port: 5672
    username: admin
    password: jhy123

logging:
  level:
    root: INFO
  console:
    enabled: true
  file:
    name: logs/myapplication.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
server:
  port: 9000
  host: 47.113.218.236
  ##host: 127.0.0.1
jwt:
  secret: riySrVRd9jKxqfixduh8  #jwt密钥
  expiration: 2592000 #过期时间（3天）